trigger:
  branches:
    include: [ "main", "dev" ]

pool:
  name: 'CyanPool'

variables:
  - group: 'GHCR'
  - name: FULL_IMAGE
    value: 'ghcr.io/nizardv/cyna-frontend'
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - name: envName
        value: 'production'
      - name: VITE_API_URL
        value: 'https://api.projet-cyna.fr'
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
      - name: envName
        value: 'staging'
      - name: VITE_API_URL
        value: 'https://api.staging.projet-cyna.fr'

stages:
- stage: CI
  displayName: 'CI — Build, Analyze, Push [ $(envName) ]'
  jobs:
  - job: Build
    steps:

    # ── 1. SonarCloud ──────────────────────────────────────────────
    - task: SonarCloudPrepare@3
      displayName: 'SonarCloud : Prepare'
      inputs:
        SonarCloud: 'SonarCloud-CYNA'
        organization: '2028di1p5g3'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '2028DI1P5G3_Cyna-Web'
        cliProjectName: 'CYNA - Frontend Web'
        cliSources: '.'
        extraProperties: |
          sonar.exclusions=**/node_modules/**,**/dist/**

    - task: SonarCloudAnalyze@3
      displayName: 'SonarCloud : Analyze'

    # ── 2. Login GHCR ──────────────────────────────────────────────
    - task: Docker@2
      displayName: 'Login GHCR'
      inputs:
        command: login
        containerRegistry: 'GHCR-Cyna-Connection'

    # ── 3. Build image avec VITE_API_URL ───────────────────────────
    - script: |
        docker build \
          --build-arg VITE_API_URL=$(VITE_API_URL) \
          -t $(FULL_IMAGE):$(envName) \
          -t $(FULL_IMAGE):sha-$(Build.SourceVersion) \
          -t $(FULL_IMAGE):build-$(Build.BuildId) \
          .
      displayName: 'Docker Build [ $(envName) ]'

    # ── 4. Push → GHCR ─────────────────────────────────────────────
    - script: |
        docker push $(FULL_IMAGE):$(envName)
        docker push $(FULL_IMAGE):sha-$(Build.SourceVersion)
        docker push $(FULL_IMAGE):build-$(Build.BuildId)
      displayName: 'Docker Push → GHCR [ $(envName) ]'